name: msal_flutter
description: A Microsoft Authentication Library wrapper for Android and iOS
version: 2.1.0
homepage: https://github.com/muljin/msal-flutter
repository: https://github.com/muljin/msal-flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: uk.co.moodio.msal_flutter
        pluginClass: MsalFlutterPlugin
      ios:
        pluginClass: MsalFlutterPlugin