name: msal_flutter_tlmn
description: A Microsoft Authentication Library wrapper for Android and iOS
version: 3.0.0-beta2
homepage: https://github.dev/ibrahimtelman/msal-flutter
repository: https://github.dev/ibrahimtelman/msal-flutter
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: uk.co.moodio.msal_flutter
        pluginClass: MsalFlutterPluginV2
      ios:
        pluginClass: MsalFlutterPlugin